name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # FRONTEND DEPLOY
      - name: Upload Frontend via FTP (Clean)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./frontend/
          server-dir: /frontend/
          # dangerous-clean-slate: true

      # BACKEND PUBLIC
      - name: Upload Backend Public via FTP (Clean)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./backend/public/
          server-dir: /public/

      # BACKEND CONFIG
      - name: Create .env on server (Backend)
        run: |
          mkdir -p ./backend/config
          echo "${{ secrets.ENV_CONTENTS }}" > ./backend/config/.env

      - name: Upload Backend Config via FTP (Clean)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./backend/config/
          server-dir: /backend/config/
          # dangerous-clean-slate: true

      # BACKEND SCRAPERS
      - name: Upload Backend Scrapers via FTP (Clean)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./backend/scrapers/
          server-dir: /backend/scrapers/
          # dangerous-clean-slate: true

      # BACKEND VENDOR
      - name: Upload Backend Vendor via FTP (Clean)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./backend/vendor/
          server-dir: /backend/vendor/
          # dangerous-clean-slate: true
